server:
  port: 9090

spring:
  application:
    name: msvc-curse
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:curseDb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-ui

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka